# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: object.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import geometry_pb2 as geometry__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='object.proto',
  package='perception',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cobject.proto\x12\nperception\x1a\x0egeometry.proto\"\x99\x02\n\tImageInfo\x12+\n\x08\x64\x65t_rect\x18\x01 \x01(\x0b\x32\x19.perception.common.Rect2f\x12,\n\ttail_rect\x18\x02 \x01(\x0b\x32\x19.perception.common.Rect2f\x12+\n\x08reg_rect\x18\x03 \x01(\x0b\x32\x19.perception.common.Rect2f\x12-\n\ntrack_rect\x18\x04 \x01(\x0b\x32\x19.perception.common.Rect2f\x12.\n\x0bsmooth_rect\x18\x05 \x01(\x0b\x32\x19.perception.common.Rect2f\x12%\n\x03\x62ox\x18\x06 \x01(\x0b\x32\x18.perception.common.Box3D\"\xae\x02\n\tWorldInfo\x12\'\n\x03vel\x18\x01 \x01(\x0b\x32\x1a.perception.common.Point3D\x12+\n\x07rel_vel\x18\x02 \x01(\x0b\x32\x1a.perception.common.Point3D\x12\'\n\x03\x61\x63\x63\x18\x03 \x01(\x0b\x32\x1a.perception.common.Point3D\x12\'\n\x03pos\x18\x04 \x01(\x0b\x32\x1a.perception.common.Point3D\x12\'\n\x04size\x18\x05 \x01(\x0b\x32\x19.perception.common.Size3D\x12)\n\x05\x61ngle\x18\x06 \x01(\x0b\x32\x1a.perception.common.Angle3f\x12%\n\x03\x62ox\x18\x07 \x01(\x0b\x32\x18.perception.common.Box3D\"D\n\nSourceInfo\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x11\n\tframe_num\x18\x02 \x01(\x05\x12\x10\n\x08\x66rame_id\x18\x03 \x01(\x05\"\xce\x01\n\x06Object\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x0b\n\x03\x63ls\x18\x03 \x01(\x05\x12\x0f\n\x07pos_cls\x18\x04 \x01(\x05\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12\x11\n\tframe_cnt\x18\x06 \x01(\x05\x12\x11\n\tlife_time\x18\x07 \x01(\x05\x12\'\n\x08img_info\x18\x08 \x01(\x0b\x32\x15.perception.ImageInfo\x12)\n\nworld_info\x18\t \x01(\x0b\x32\x15.perception.WorldInfo\"[\n\nObjectList\x12 \n\x04list\x18\x01 \x03(\x0b\x32\x12.perception.Object\x12+\n\x0bsource_info\x18\x02 \x01(\x0b\x32\x16.perception.SourceInfo*\x94\x01\n\nObjectType\x12\x16\n\x12ObjectType_Vehicle\x10\x00\x12\x19\n\x15ObjectType_Pedestrian\x10\x01\x12\x1a\n\x16ObjectType_TrafficSign\x10\x02\x12\x1b\n\x17ObjectType_TrafficLight\x10\x03\x12\x1a\n\x16ObjectType_SpeedCamera\x10\x04\x62\x06proto3'
  ,
  dependencies=[geometry__pb2.DESCRIPTOR,])

_OBJECTTYPE = _descriptor.EnumDescriptor(
  name='ObjectType',
  full_name='perception.ObjectType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ObjectType_Vehicle', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ObjectType_Pedestrian', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ObjectType_TrafficSign', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ObjectType_TrafficLight', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ObjectType_SpeedCamera', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=1006,
  serialized_end=1154,
)
_sym_db.RegisterEnumDescriptor(_OBJECTTYPE)

ObjectType = enum_type_wrapper.EnumTypeWrapper(_OBJECTTYPE)
ObjectType_Vehicle = 0
ObjectType_Pedestrian = 1
ObjectType_TrafficSign = 2
ObjectType_TrafficLight = 3
ObjectType_SpeedCamera = 4



_IMAGEINFO = _descriptor.Descriptor(
  name='ImageInfo',
  full_name='perception.ImageInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='det_rect', full_name='perception.ImageInfo.det_rect', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tail_rect', full_name='perception.ImageInfo.tail_rect', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reg_rect', full_name='perception.ImageInfo.reg_rect', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='track_rect', full_name='perception.ImageInfo.track_rect', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='smooth_rect', full_name='perception.ImageInfo.smooth_rect', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='box', full_name='perception.ImageInfo.box', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=326,
)


_WORLDINFO = _descriptor.Descriptor(
  name='WorldInfo',
  full_name='perception.WorldInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vel', full_name='perception.WorldInfo.vel', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rel_vel', full_name='perception.WorldInfo.rel_vel', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='acc', full_name='perception.WorldInfo.acc', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pos', full_name='perception.WorldInfo.pos', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='size', full_name='perception.WorldInfo.size', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='angle', full_name='perception.WorldInfo.angle', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='box', full_name='perception.WorldInfo.box', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=631,
)


_SOURCEINFO = _descriptor.Descriptor(
  name='SourceInfo',
  full_name='perception.SourceInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_path', full_name='perception.SourceInfo.file_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame_num', full_name='perception.SourceInfo.frame_num', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='perception.SourceInfo.frame_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=633,
  serialized_end=701,
)


_OBJECT = _descriptor.Descriptor(
  name='Object',
  full_name='perception.Object',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='perception.Object.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='perception.Object.type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cls', full_name='perception.Object.cls', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pos_cls', full_name='perception.Object.pos_cls', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='perception.Object.confidence', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame_cnt', full_name='perception.Object.frame_cnt', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='life_time', full_name='perception.Object.life_time', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='img_info', full_name='perception.Object.img_info', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='world_info', full_name='perception.Object.world_info', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=704,
  serialized_end=910,
)


_OBJECTLIST = _descriptor.Descriptor(
  name='ObjectList',
  full_name='perception.ObjectList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='list', full_name='perception.ObjectList.list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source_info', full_name='perception.ObjectList.source_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=912,
  serialized_end=1003,
)

_IMAGEINFO.fields_by_name['det_rect'].message_type = geometry__pb2._RECT2F
_IMAGEINFO.fields_by_name['tail_rect'].message_type = geometry__pb2._RECT2F
_IMAGEINFO.fields_by_name['reg_rect'].message_type = geometry__pb2._RECT2F
_IMAGEINFO.fields_by_name['track_rect'].message_type = geometry__pb2._RECT2F
_IMAGEINFO.fields_by_name['smooth_rect'].message_type = geometry__pb2._RECT2F
_IMAGEINFO.fields_by_name['box'].message_type = geometry__pb2._BOX3D
_WORLDINFO.fields_by_name['vel'].message_type = geometry__pb2._POINT3D
_WORLDINFO.fields_by_name['rel_vel'].message_type = geometry__pb2._POINT3D
_WORLDINFO.fields_by_name['acc'].message_type = geometry__pb2._POINT3D
_WORLDINFO.fields_by_name['pos'].message_type = geometry__pb2._POINT3D
_WORLDINFO.fields_by_name['size'].message_type = geometry__pb2._SIZE3D
_WORLDINFO.fields_by_name['angle'].message_type = geometry__pb2._ANGLE3F
_WORLDINFO.fields_by_name['box'].message_type = geometry__pb2._BOX3D
_OBJECT.fields_by_name['img_info'].message_type = _IMAGEINFO
_OBJECT.fields_by_name['world_info'].message_type = _WORLDINFO
_OBJECTLIST.fields_by_name['list'].message_type = _OBJECT
_OBJECTLIST.fields_by_name['source_info'].message_type = _SOURCEINFO
DESCRIPTOR.message_types_by_name['ImageInfo'] = _IMAGEINFO
DESCRIPTOR.message_types_by_name['WorldInfo'] = _WORLDINFO
DESCRIPTOR.message_types_by_name['SourceInfo'] = _SOURCEINFO
DESCRIPTOR.message_types_by_name['Object'] = _OBJECT
DESCRIPTOR.message_types_by_name['ObjectList'] = _OBJECTLIST
DESCRIPTOR.enum_types_by_name['ObjectType'] = _OBJECTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageInfo = _reflection.GeneratedProtocolMessageType('ImageInfo', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEINFO,
  '__module__' : 'object_pb2'
  # @@protoc_insertion_point(class_scope:perception.ImageInfo)
  })
_sym_db.RegisterMessage(ImageInfo)

WorldInfo = _reflection.GeneratedProtocolMessageType('WorldInfo', (_message.Message,), {
  'DESCRIPTOR' : _WORLDINFO,
  '__module__' : 'object_pb2'
  # @@protoc_insertion_point(class_scope:perception.WorldInfo)
  })
_sym_db.RegisterMessage(WorldInfo)

SourceInfo = _reflection.GeneratedProtocolMessageType('SourceInfo', (_message.Message,), {
  'DESCRIPTOR' : _SOURCEINFO,
  '__module__' : 'object_pb2'
  # @@protoc_insertion_point(class_scope:perception.SourceInfo)
  })
_sym_db.RegisterMessage(SourceInfo)

Object = _reflection.GeneratedProtocolMessageType('Object', (_message.Message,), {
  'DESCRIPTOR' : _OBJECT,
  '__module__' : 'object_pb2'
  # @@protoc_insertion_point(class_scope:perception.Object)
  })
_sym_db.RegisterMessage(Object)

ObjectList = _reflection.GeneratedProtocolMessageType('ObjectList', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTLIST,
  '__module__' : 'object_pb2'
  # @@protoc_insertion_point(class_scope:perception.ObjectList)
  })
_sym_db.RegisterMessage(ObjectList)


# @@protoc_insertion_point(module_scope)
